/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Board Game Pieces.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Carved.geometry}
        material={materials['AI Gen Texture - Sci-Fi White Orange_mat_0_0_2.000']}
        position={[0, -0.003, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Carved_1.geometry}
          material={materials['AI Gen Texture - Sci-Fi White Orange_mat_0_0_2.000']}
          position={[0, -0.003, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Carved_2.geometry}
            material={materials['AI Gen Texture - Sci-Fi White Orange_mat_0_0_2.000']}
            position={[0, -0.003, 0]}
          />
        </mesh>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.body.geometry}
        material={materials['AI Gen Texture - Sci-Fi White Orange_mat_0_0_2.000']}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.neck.geometry}
          material={materials['AI Gen Texture - Sci-Fi White Orange_mat_0_0_2.000']}
          position={[0, 0.015, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.head.geometry}
            material={materials['AI Gen Texture - Sci-Fi White Orange_mat_0_0_2.000']}
            position={[0, 0.002, 0]}
          />
        </mesh>
      </mesh>
    </group>
  )
}

useGLTF.preload('/Board Game Pieces.glb')


rembrandt

city
Made by @NikkitaFTW & contributors inspired by the gltfjsx cli

